services:
  dashboard:
    build: .
    volumes:
      - ./app/server/data:/mymanager/app/server/data
      - ./app/server/uploads:/mymanager/app/server/uploads
      - ./app/server/.env:/mymanager/app/server/.env
    env_file:
      - app/server/.env
    environment:
      - NODE_ENV=production
      - PORT=7293
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      npm-host-bridge:
        ipv4_address: 172.18.0.2

networks:
  npm-host-bridge:
    external: true
